"""
CubeSat attitude control with PPO adaptive PID gain scheduling.

Purpose
-------
This script implements a simplified rigid-body CubeSat attitude model and compares:

1) Fixed PID baseline
2) PPO adaptive PID gain scheduler

The PPO agent does NOT command the reaction-wheel torque directly.
Instead, it commands normalized gain multipliers:

    action = [aP, aD, aI] in [-1, 1]^3

which are mapped to:

    Kp(t) = alphaP(t) * Kp_nom
    Kd(t) = alphaD(t) * Kd_nom
    Ki(t) = alphaI(t) * Ki_nom

The physical torque is still generated by an interpretable quaternion PID law:

    u = -Kp(t) * sign(q4) * q_vec
        -Kd(t) * omega
        -Ki(t) * integral(sign(q4) * q_vec)
        + omega x I omega

Dynamics
--------
    I * omega_dot = u - omega x (I omega)
    q_dot = 0.5 * Omega(omega) q

Quaternion convention
---------------------
Scalar-last quaternion:
    q = [q1, q2, q3, q4]

Run
---
    python cubesat_adaptive_pid_ppo.py

By default, PPO training is OFF so the script runs immediately.
Set TRAIN_RL = True in main() to train the adaptive gain scheduler.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from typing import Dict, Optional, Tuple

import gymnasium as gym
import matplotlib.pyplot as plt
import numpy as np
from gymnasium import spaces


# ============================================================
# 1. Quaternion utilities
# ============================================================


def quat_normalize(q: np.ndarray) -> np.ndarray:
    q = np.asarray(q, dtype=float).reshape(4)
    n = np.linalg.norm(q)
    if n < 1e-12:
        return np.array([0.0, 0.0, 0.0, 1.0])
    return q / n


def quat_conjugate(q: np.ndarray) -> np.ndarray:
    q = quat_normalize(q)
    return np.array([-q[0], -q[1], -q[2], q[3]])


def quat_multiply(q: np.ndarray, p: np.ndarray) -> np.ndarray:
    """Hamilton product, scalar-last convention."""
    q = np.asarray(q, dtype=float).reshape(4)
    p = np.asarray(p, dtype=float).reshape(4)

    qx, qy, qz, qw = q
    px, py, pz, pw = p

    v = np.array([
        qw * px + pw * qx + qy * pz - qz * py,
        qw * py + pw * qy + qz * px - qx * pz,
        qw * pz + pw * qz + qx * py - qy * px,
    ])
    s = qw * pw - qx * px - qy * py - qz * pz

    return quat_normalize(np.array([v[0], v[1], v[2], s]))


def quat_from_axis_angle(axis: np.ndarray, angle_rad: float) -> np.ndarray:
    axis = np.asarray(axis, dtype=float).reshape(3)
    axis_norm = np.linalg.norm(axis)
    if axis_norm < 1e-12:
        axis = np.array([1.0, 0.0, 0.0])
    else:
        axis = axis / axis_norm

    q_vec = axis * np.sin(angle_rad / 2.0)
    q_sca = np.cos(angle_rad / 2.0)
    return quat_normalize(np.array([q_vec[0], q_vec[1], q_vec[2], q_sca]))


def random_error_quaternion(
    min_angle_deg: float = 30.0,
    max_angle_deg: float = 150.0,
) -> np.ndarray:
    """Random attitude error sampled through axis-angle."""
    axis = np.random.normal(size=3)
    axis = axis / (np.linalg.norm(axis) + 1e-12)
    angle = np.deg2rad(np.random.uniform(min_angle_deg, max_angle_deg))
    return quat_from_axis_angle(axis, angle)


def pointing_error_deg(q_err: np.ndarray) -> float:
    """Pointing error theta = 2 acos(|q4|), returned in degrees."""
    q_err = quat_normalize(q_err)
    q4 = np.clip(np.abs(q_err[3]), 0.0, 1.0)
    theta = 2.0 * np.arccos(q4)
    return float(np.rad2deg(theta))


def omega_matrix(w: np.ndarray) -> np.ndarray:
    """Omega(w) matrix for scalar-last quaternion q_dot = 0.5 Omega(w) q."""
    wx, wy, wz = np.asarray(w, dtype=float).reshape(3)
    return np.array([
        [0.0, wz, -wy, wx],
        [-wz, 0.0, wx, wy],
        [wy, -wx, 0.0, wz],
        [-wx, -wy, -wz, 0.0],
    ])


# ============================================================
# 2. Rigid-body dynamics
# ============================================================


def rigid_body_derivative(x: np.ndarray, u: np.ndarray, inertia: np.ndarray) -> np.ndarray:
    """State x = [q1, q2, q3, q4, wx, wy, wz]."""
    x = np.asarray(x, dtype=float).reshape(7)
    u = np.asarray(u, dtype=float).reshape(3)

    q = quat_normalize(x[0:4])
    w = x[4:7]

    Iw = inertia @ w
    q_dot = 0.5 * omega_matrix(w) @ q
    w_dot = np.linalg.solve(inertia, u - np.cross(w, Iw))

    return np.concatenate([q_dot, w_dot])


def rk4_step(x: np.ndarray, u: np.ndarray, dt: float, inertia: np.ndarray) -> np.ndarray:
    k1 = rigid_body_derivative(x, u, inertia)
    k2 = rigid_body_derivative(x + 0.5 * dt * k1, u, inertia)
    k3 = rigid_body_derivative(x + 0.5 * dt * k2, u, inertia)
    k4 = rigid_body_derivative(x + dt * k3, u, inertia)

    x_next = x + (dt / 6.0) * (k1 + 2.0 * k2 + 2.0 * k3 + k4)
    x_next[0:4] = quat_normalize(x_next[0:4])
    return x_next


# ============================================================
# 3. Gymnasium environment: PPO adaptive PID gain scheduler
# ============================================================


@dataclass
class GainBounds:
    P: Tuple[float, float] = (0.2, 3.0)
    D: Tuple[float, float] = (0.2, 3.0)
    I: Tuple[float, float] = (0.0, 2.0)


class CubeSatAdaptivePIDGainEnv(gym.Env):
    """
    Environment where the RL action adapts PID gain multipliers.

    Observation:
        obs = [q1, q2, q3, q4, wx, wy, wz, int_ex, int_ey, int_ez]

    Action:
        action = [aP, aD, aI] in [-1, 1]^3
    """

    metadata = {"render_modes": []}

    def __init__(
        self,
        inertia: Optional[np.ndarray] = None,
        dt: float = 0.1,
        max_time: float = 180.0,
        umax: float = 3e-4,
        random_initial_attitude: bool = True,
        random_initial_rate: bool = True,
        initial_angle_range_deg: Tuple[float, float] = (30.0, 150.0),
        w0_std_deg_s: float = 1.0,
        wn_nom: float = 0.08,
        zeta_nom: float = 0.9,
        ki_ratio_nom: float = 0.03,
        integral_limit: float = 0.5,
        gain_bounds: Optional[Dict[str, Tuple[float, float]]] = None,
        reward_weights: Optional[Dict[str, float]] = None,
        use_gyro_compensation: bool = True,
    ):
        super().__init__()

        if inertia is None:
            inertia = np.diag([0.058816667, 0.054000375, 0.011250375])

        self.I = np.asarray(inertia, dtype=float)
        self.dt = float(dt)
        self.max_time = float(max_time)
        self.max_steps = int(np.round(max_time / dt))
        self.umax = float(umax)

        self.random_initial_attitude = bool(random_initial_attitude)
        self.random_initial_rate = bool(random_initial_rate)
        self.initial_angle_range_deg = initial_angle_range_deg
        self.w0_std = np.deg2rad(w0_std_deg_s)
        self.use_gyro_compensation = bool(use_gyro_compensation)
        self.integral_limit = float(integral_limit)

        I_diag = np.diag(self.I)
        self.Kp_nom = I_diag * wn_nom**2
        self.Kd_nom = 2.0 * zeta_nom * I_diag * wn_nom
        self.Ki_nom = ki_ratio_nom * self.Kp_nom

        if gain_bounds is None:
            gain_bounds = {"P": (0.2, 3.0), "D": (0.2, 3.0), "I": (0.0, 2.0)}
        self.gain_bounds = gain_bounds

        if reward_weights is None:
            reward_weights = {
                "theta": 5.0,
                "omega": 0.2,
                "torque": 0.02,
                "integral": 0.02,
                "gain_rate": 0.01,
                "bonus_5deg": 2.0,
                "bonus_025deg": 8.0,
            }
        self.reward_weights = reward_weights

        high_obs = np.array(
            [1, 1, 1, 1, 10, 10, 10, integral_limit, integral_limit, integral_limit],
            dtype=np.float32,
        )
        self.observation_space = spaces.Box(low=-high_obs, high=high_obs, dtype=np.float32)
        self.action_space = spaces.Box(
            low=-np.ones(3, dtype=np.float32),
            high=np.ones(3, dtype=np.float32),
            dtype=np.float32,
        )

        self.x = np.zeros(7)
        self.int_err = np.zeros(3)
        self.t = 0.0
        self.step_count = 0
        self.prev_alpha = np.ones(3)

    @staticmethod
    def _scale_action(a: float, low: float, high: float) -> float:
        return low + 0.5 * (a + 1.0) * (high - low)

    def _map_action_to_gains(self, action: np.ndarray):
        action = np.clip(np.asarray(action, dtype=float).reshape(3), -1.0, 1.0)

        alphaP = self._scale_action(action[0], *self.gain_bounds["P"])
        alphaD = self._scale_action(action[1], *self.gain_bounds["D"])
        alphaI = self._scale_action(action[2], *self.gain_bounds["I"])
        alpha = np.array([alphaP, alphaD, alphaI])

        Kp = alphaP * self.Kp_nom
        Kd = alphaD * self.Kd_nom
        Ki = alphaI * self.Ki_nom
        return Kp, Kd, Ki, alpha

    def _get_obs(self) -> np.ndarray:
        return np.concatenate([self.x, self.int_err]).astype(np.float32)

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)

        if self.random_initial_attitude:
            q0 = random_error_quaternion(*self.initial_angle_range_deg)
        else:
            q0 = quat_normalize(np.array([0.2226, 0.1019, -0.9678, 0.0589]))

        if self.random_initial_rate:
            w0 = np.random.normal(loc=0.0, scale=self.w0_std, size=3)
        else:
            w0 = np.zeros(3)

        self.x = np.concatenate([q0, w0]).astype(float)
        self.int_err = np.zeros(3)
        self.t = 0.0
        self.step_count = 0
        self.prev_alpha = np.ones(3)
        return self._get_obs(), {}

    def step(self, action: np.ndarray):
        Kp, Kd, Ki, alpha = self._map_action_to_gains(action)

        q = quat_normalize(self.x[0:4])
        w = self.x[4:7]
        q_vec = q[0:3]
        q4 = q[3]

        # Shortest-path quaternion vector error.
        e_q = np.sign(q4 + 1e-12) * q_vec

        # Integral term with anti-windup clipping.
        self.int_err = np.clip(
            self.int_err + e_q * self.dt,
            -self.integral_limit,
            self.integral_limit,
        )

        # Adaptive PID torque.
        u = -Kp * e_q - Kd * w - Ki * self.int_err
        if self.use_gyro_compensation:
            u += np.cross(w, self.I @ w)
        u = np.clip(u, -self.umax, self.umax)

        # Propagate dynamics.
        self.x = rk4_step(self.x, u, self.dt, self.I)
        self.t += self.dt
        self.step_count += 1

        q_next = self.x[0:4]
        w_next = self.x[4:7]
        theta_deg = pointing_error_deg(q_next)
        theta_rad = np.deg2rad(theta_deg)
        w_norm = np.linalg.norm(w_next)
        u_norm = np.linalg.norm(u)
        int_norm = np.linalg.norm(self.int_err)

        gain_rate_penalty = np.linalg.norm(alpha - self.prev_alpha) ** 2
        self.prev_alpha = alpha.copy()

        rw = self.reward_weights
        reward = (
            -rw["theta"] * theta_rad**2
            -rw["omega"] * w_norm**2
            -rw["torque"] * (u_norm / self.umax) ** 2
            -rw["integral"] * int_norm**2
            -rw["gain_rate"] * gain_rate_penalty
        )
        if theta_deg < 5.0:
            reward += rw["bonus_5deg"]
        if theta_deg < 0.25:
            reward += rw["bonus_025deg"]

        terminated = False
        truncated = self.step_count >= self.max_steps
        if w_norm > 1.0:
            terminated = True
            reward -= 50.0

        info = {
            "time": self.t,
            "theta_deg": theta_deg,
            "omega_norm": w_norm,
            "torque": u.copy(),
            "torque_norm": u_norm,
            "alphaP": alpha[0],
            "alphaD": alpha[1],
            "alphaI": alpha[2],
            "Kp": Kp.copy(),
            "Kd": Kd.copy(),
            "Ki": Ki.copy(),
            "integral_error": self.int_err.copy(),
        }
        return self._get_obs(), float(reward), terminated, truncated, info


# ============================================================
# 4. Fixed PID baseline
# ============================================================


class FixedPIDController:
    """Fixed-gain PID baseline for comparison."""

    def __init__(
        self,
        inertia: np.ndarray,
        wn: float = 0.08,
        zeta: float = 0.9,
        ki_ratio: float = 0.03,
        umax: float = 3e-4,
        integral_limit: float = 0.5,
        use_gyro_compensation: bool = True,
    ):
        self.I = np.asarray(inertia, dtype=float)
        self.umax = float(umax)
        self.integral_limit = float(integral_limit)
        self.use_gyro_compensation = bool(use_gyro_compensation)

        I_diag = np.diag(self.I)
        self.Kp = I_diag * wn**2
        self.Kd = 2.0 * zeta * I_diag * wn
        self.Ki = ki_ratio * self.Kp
        self.int_err = np.zeros(3)

    def reset(self):
        self.int_err = np.zeros(3)

    def __call__(self, obs: np.ndarray, dt: float = 0.1) -> np.ndarray:
        q = quat_normalize(obs[0:4])
        w = np.asarray(obs[4:7], dtype=float)
        e_q = np.sign(q[3] + 1e-12) * q[0:3]

        self.int_err = np.clip(
            self.int_err + e_q * dt,
            -self.integral_limit,
            self.integral_limit,
        )

        u = -self.Kp * e_q - self.Kd * w - self.Ki * self.int_err
        if self.use_gyro_compensation:
            u += np.cross(w, self.I @ w)
        return np.clip(u, -self.umax, self.umax)


# ============================================================
# 5. Rollout utilities
# ============================================================


def _empty_history():
    return {
        "time": [],
        "theta_deg": [],
        "omega_norm": [],
        "torque": [],
        "reward": [],
        "q": [],
        "w": [],
        "alpha": [],
    }


def _history_to_arrays(hist: dict) -> dict:
    return {k: np.array(v) for k, v in hist.items()}


def rollout_fixed_pid(env: CubeSatAdaptivePIDGainEnv, controller: FixedPIDController) -> dict:
    """Rollout for fixed PID controller. It applies torque directly."""
    obs, _ = env.reset()
    controller.reset()
    hist = _empty_history()
    done = False

    while not done:
        u = controller(obs, dt=env.dt)

        env.x = rk4_step(env.x, u, env.dt, env.I)
        env.t += env.dt
        env.step_count += 1

        q = env.x[0:4]
        w = env.x[4:7]
        theta_deg = pointing_error_deg(q)
        theta_rad = np.deg2rad(theta_deg)
        w_norm = np.linalg.norm(w)
        u_norm = np.linalg.norm(u)

        rw = env.reward_weights
        reward = (
            -rw["theta"] * theta_rad**2
            -rw["omega"] * w_norm**2
            -rw["torque"] * (u_norm / env.umax) ** 2
        )
        if theta_deg < 5.0:
            reward += rw["bonus_5deg"]
        if theta_deg < 0.25:
            reward += rw["bonus_025deg"]

        terminated = w_norm > 1.0
        truncated = env.step_count >= env.max_steps
        if terminated:
            reward -= 50.0
        done = terminated or truncated

        obs = env._get_obs()

        hist["time"].append(env.t)
        hist["theta_deg"].append(theta_deg)
        hist["omega_norm"].append(w_norm)
        hist["torque"].append(u.copy())
        hist["reward"].append(float(reward))
        hist["q"].append(q.copy())
        hist["w"].append(w.copy())
        hist["alpha"].append([1.0, 1.0, 1.0])

    return _history_to_arrays(hist)


def rollout_adaptive_ppo(env: CubeSatAdaptivePIDGainEnv, model) -> dict:
    """Rollout for trained PPO gain scheduler."""
    obs, _ = env.reset()
    hist = _empty_history()
    done = False

    while not done:
        action, _ = model.predict(obs, deterministic=True)
        obs, reward, terminated, truncated, info = env.step(action)
        done = terminated or truncated

        hist["time"].append(info["time"])
        hist["theta_deg"].append(info["theta_deg"])
        hist["omega_norm"].append(info["omega_norm"])
        hist["torque"].append(info["torque"])
        hist["reward"].append(float(reward))
        hist["q"].append(obs[0:4].copy())
        hist["w"].append(obs[4:7].copy())
        hist["alpha"].append([info["alphaP"], info["alphaD"], info["alphaI"]])

    return _history_to_arrays(hist)


# ============================================================
# 6. Metrics and plots
# ============================================================


def compute_metrics(data: dict, threshold_deg: float = 5.0) -> dict:
    t = data["time"]
    theta = data["theta_deg"]
    w_norm = data["omega_norm"]
    torque = data["torque"]

    settling_time = np.nan
    if len(theta) > 0 and np.any(theta < threshold_deg):
        for k in range(len(theta)):
            if np.all(theta[k:] < threshold_deg):
                settling_time = t[k]
                break

    dt = np.mean(np.diff(t)) if len(t) > 1 else 0.0
    torque_norm = np.linalg.norm(torque, axis=1)

    return {
        "final_pointing_error_deg": float(theta[-1]),
        "max_pointing_error_deg": float(np.max(theta)),
        "final_omega_norm_rad_s": float(w_norm[-1]),
        "settling_time_5deg_s": float(settling_time) if np.isfinite(settling_time) else np.nan,
        "max_torque_Nm": float(np.max(np.abs(torque))),
        "torque_rms_Nm": float(np.sqrt(np.mean(torque_norm**2))),
        "torque_integral_Nm_s": float(np.sum(torque_norm) * dt),
        "total_reward": float(np.sum(data["reward"])),
    }


def print_metrics(name: str, metrics: dict) -> None:
    print(f"\n=== {name} metrics ===")
    for key, value in metrics.items():
        print(f"{key:30s}: {value:.6e}")


def set_plot_defaults() -> None:
    plt.rcParams.update({
        "font.size": 11,
        "axes.grid": True,
        "grid.alpha": 0.35,
        "figure.figsize": (9, 5),
        "lines.linewidth": 1.8,
    })


def plot_adaptive_pid_results(fixed_data: dict, adaptive_data: Optional[dict] = None, save_dir: str = "results") -> None:
    os.makedirs(save_dir, exist_ok=True)
    set_plot_defaults()

    # Pointing error.
    plt.figure()
    plt.plot(fixed_data["time"], fixed_data["theta_deg"], label="Fixed PID")
    if adaptive_data is not None:
        plt.plot(adaptive_data["time"], adaptive_data["theta_deg"], label="PPO adaptive PID")
    plt.axhline(5.0, linestyle="--", label="5 deg requirement")
    plt.xlabel("Time [s]")
    plt.ylabel("Pointing error [deg]")
    plt.title("Pointing error: fixed PID vs adaptive PID")
    plt.legend()
    plt.tight_layout()
    plt.savefig(os.path.join(save_dir, "adaptive_pid_pointing_error.png"), dpi=200)

    # Angular velocity norm.
    plt.figure()
    plt.plot(fixed_data["time"], fixed_data["omega_norm"], label="Fixed PID")
    if adaptive_data is not None:
        plt.plot(adaptive_data["time"], adaptive_data["omega_norm"], label="PPO adaptive PID")
    plt.xlabel("Time [s]")
    plt.ylabel(r"$||\omega||$ [rad/s]")
    plt.title("Angular velocity norm")
    plt.legend()
    plt.tight_layout()
    plt.savefig(os.path.join(save_dir, "adaptive_pid_omega_norm.png"), dpi=200)

    # Torque components.
    labels = [r"$u_x$", r"$u_y$", r"$u_z$"]
    plt.figure()
    for i in range(3):
        plt.plot(fixed_data["time"], fixed_data["torque"][:, i], label=f"Fixed PID {labels[i]}")
    if adaptive_data is not None:
        for i in range(3):
            plt.plot(
                adaptive_data["time"],
                adaptive_data["torque"][:, i],
                linestyle="--",
                label=f"Adaptive PID {labels[i]}",
            )
    plt.xlabel("Time [s]")
    plt.ylabel("Reaction wheel torque [N m]")
    plt.title("Reaction wheel torque")
    plt.legend(ncol=2)
    plt.tight_layout()
    plt.savefig(os.path.join(save_dir, "adaptive_pid_torque.png"), dpi=200)

    # Gain multipliers.
    if adaptive_data is not None:
        plt.figure()
        plt.plot(adaptive_data["time"], adaptive_data["alpha"][:, 0], label=r"$\alpha_P$")
        plt.plot(adaptive_data["time"], adaptive_data["alpha"][:, 1], label=r"$\alpha_D$")
        plt.plot(adaptive_data["time"], adaptive_data["alpha"][:, 2], label=r"$\alpha_I$")
        plt.xlabel("Time [s]")
        plt.ylabel("Gain multiplier [-]")
        plt.title("PPO adaptive gain multipliers")
        plt.legend()
        plt.tight_layout()
        plt.savefig(os.path.join(save_dir, "adaptive_pid_gain_multipliers.png"), dpi=200)

    plt.show()


# ============================================================
# 7. PPO training
# ============================================================


def train_ppo_gain_scheduler(
    total_timesteps: int = 300_000,
    save_path: str = "results/ppo_adaptive_pid_gains",
):
    """Train PPO to adapt PID gain multipliers."""
    try:
        from stable_baselines3 import PPO
        from stable_baselines3.common.monitor import Monitor
        from stable_baselines3.common.vec_env import DummyVecEnv
    except ImportError as exc:
        raise ImportError(
            "Stable-Baselines3 is not installed. Install it with: "
            "pip install stable-baselines3"
        ) from exc

    def make_env():
        env = CubeSatAdaptivePIDGainEnv(
            dt=0.1,
            max_time=120.0,
            umax=3e-4,
            random_initial_attitude=True,
            random_initial_rate=True,
            initial_angle_range_deg=(30.0, 150.0),
            w0_std_deg_s=1.0,
            wn_nom=0.08,
            zeta_nom=0.9,
            ki_ratio_nom=0.03,
        )
        return Monitor(env)

    vec_env = DummyVecEnv([make_env])
    policy_kwargs = dict(net_arch=dict(pi=[64, 64], vf=[64, 64]))

    model = PPO(
        policy="MlpPolicy",
        env=vec_env,
        learning_rate=3e-4,
        n_steps=2048,
        batch_size=128,
        n_epochs=10,
        gamma=0.995,
        gae_lambda=0.95,
        clip_range=0.2,
        ent_coef=1e-3,
        policy_kwargs=policy_kwargs,
        verbose=1,
    )

    model.learn(total_timesteps=total_timesteps)
    os.makedirs(os.path.dirname(save_path), exist_ok=True)
    model.save(save_path)
    return model


# ============================================================
# 8. Main
# ============================================================


def main() -> None:
    os.makedirs("results", exist_ok=True)

    inertia = np.diag([0.058816667, 0.054000375, 0.011250375])
    umax = 3e-4

    # Set this to True only when stable-baselines3 is installed.
    # First try with 50_000 timesteps, then increase.
    TRAIN_RL = False
    TOTAL_TIMESTEPS = 50_000

    # Fixed PID baseline.
    env_fixed = CubeSatAdaptivePIDGainEnv(
        inertia=inertia,
        dt=0.1,
        max_time=300.0,
        umax=umax,
        random_initial_attitude=False,
        random_initial_rate=False,
        wn_nom=0.08,
        zeta_nom=0.9,
        ki_ratio_nom=0.03,
    )

    fixed_pid = FixedPIDController(
        inertia=inertia,
        wn=0.08,
        zeta=0.9,
        ki_ratio=0.03,
        umax=umax,
        integral_limit=0.5,
        use_gyro_compensation=True,
    )

    fixed_data = rollout_fixed_pid(env_fixed, fixed_pid)
    fixed_metrics = compute_metrics(fixed_data)
    print_metrics("Fixed PID baseline", fixed_metrics)

    adaptive_data = None

    if TRAIN_RL:
        model = train_ppo_gain_scheduler(
            total_timesteps=TOTAL_TIMESTEPS,
            save_path="results/ppo_adaptive_pid_gains",
        )

        env_adaptive_eval = CubeSatAdaptivePIDGainEnv(
            inertia=inertia,
            dt=0.1,
            max_time=300.0,
            umax=umax,
            random_initial_attitude=False,
            random_initial_rate=False,
            wn_nom=0.08,
            zeta_nom=0.9,
            ki_ratio_nom=0.03,
        )

        adaptive_data = rollout_adaptive_ppo(env_adaptive_eval, model)
        adaptive_metrics = compute_metrics(adaptive_data)
        print_metrics("PPO adaptive PID", adaptive_metrics)

    plot_adaptive_pid_results(
        fixed_data=fixed_data,
        adaptive_data=adaptive_data,
        save_dir="results",
    )


if __name__ == "__main__":
    main()
